import { describe, expect, test } from 'bun:test';
import {
  isDnsName,
  renderConfig,
  routerName,
  validateHosts,
  type RenderOptions,
} from '../src/render.ts';

const OPTS: RenderOptions = {
  storeDomain: 'vendua.com.br',
  deny: ['painel.example.com', 'crm.example.com', ' Site.Example.com '],
  service: 'vendua-edge@docker',
  middleware: 'vendua-edge-https@docker',
  resolver: 'letsencrypt',
};

describe('renderConfig', () => {
  test('two routers per host, sorted, everything quoted', () => {
    const yml = renderConfig(['www.loja.com.br', 'loja.com.br'], OPTS);
    const a = routerName('loja.com.br');
    const b = routerName('www.loja.com.br');
    expect(a).toMatch(/^vendua-cd-loja-com-br-[0-9a-f]{8}$/);
    expect(yml).toBe(
      [
        '# Generated by domains-sync (packages/domains-sync) from Core GET /sync/v1/custom-hosts.',
        '# Do not edit: it is rewritten whenever the list of custom domains changes (ADR 0038).',
        'http:',
        '  routers:',
        `    "${a}":`,
        '      rule: "Host(`loja.com.br`)"',
        '      entryPoints: ["websecure"]',
        '      service: "vendua-edge@docker"',
        '      priority: 2',
        '      tls:',
        '        certResolver: "letsencrypt"',
        `    "${a}-web":`,
        '      rule: "Host(`loja.com.br`)"',
        '      entryPoints: ["web"]',
        '      service: "vendua-edge@docker"',
        '      middlewares: ["vendua-edge-https@docker"]',
        '      priority: 2',
        `    "${b}":`,
        '      rule: "Host(`www.loja.com.br`)"',
        '      entryPoints: ["websecure"]',
        '      service: "vendua-edge@docker"',
        '      priority: 2',
        '      tls:',
        '        certResolver: "letsencrypt"',
        `    "${b}-web":`,
        '      rule: "Host(`www.loja.com.br`)"',
        '      entryPoints: ["web"]',
        '      service: "vendua-edge@docker"',
        '      middlewares: ["vendua-edge-https@docker"]',
        '      priority: 2',
        '',
      ].join('\n'),
    );
  });

  test('parses as YAML into the Traefik shape', () => {
    const doc = Bun.YAML.parse(renderConfig(['loja.com.br'], OPTS)) as {
      http: { routers: Record<string, Record<string, unknown>> };
    };
    const name = routerName('loja.com.br');
    expect(doc.http.routers[name]).toEqual({
      rule: 'Host(`loja.com.br`)',
      entryPoints: ['websecure'],
      service: 'vendua-edge@docker',
      priority: 2,
      tls: { certResolver: 'letsencrypt' },
    });
    expect(doc.http.routers[`${name}-web`]).toEqual({
      rule: 'Host(`loja.com.br`)',
      entryPoints: ['web'],
      service: 'vendua-edge@docker',
      middlewares: ['vendua-edge-https@docker'],
      priority: 2,
    });
  });

  test('identical input, identical bytes; an empty list is still a valid file', () => {
    expect(renderConfig(['b.com', 'a.com'], OPTS)).toBe(renderConfig(['a.com', 'b.com'], OPTS));
    const empty = renderConfig([], OPTS);
    expect(empty).toStartWith('# Generated by domains-sync');
    expect(empty).not.toContain('http');
    expect(empty.split('\n').every((l) => l === '' || l.startsWith('#'))).toBe(true);
  });

  test('router names are valid and keep look-alike hosts apart', () => {
    expect(routerName('a-b.com')).not.toBe(routerName('a.b.com'));
    expect(routerName('xn--pudim-9qa.com.br')).toMatch(/^[a-z0-9-]+$/);
    expect(routerName('loja.com.br')).toBe(routerName('loja.com.br'));
  });
});

describe('validateHosts', () => {
  test('keeps lower-case DNS names, sorted and unique', () => {
    const r = validateHosts(
      ['www.loja.com.br', 'loja.com.br', 'loja.com.br', 'xn--pudim-9qa.com'],
      OPTS,
    );
    expect(r.hosts).toEqual(['loja.com.br', 'www.loja.com.br', 'xn--pudim-9qa.com']);
    expect(r.dropped).toEqual([]);
  });

  test('drops what is not a lower-case DNS name', () => {
    const bad = [
      'Loja.com.br',
      'loja',
      'localhost',
      'app.localhost',
      '-loja.com.br',
      'loja-.com.br',
      'lo_ja.com.br',
      '1.2.3.4',
      'loja.c0m',
      'loja..com',
      '.loja.com',
      'loja.com.',
      'loja.com/x',
      'loja.com`) || Host(`painel.example.com',
      `${'a'.repeat(64)}.com`,
      `${'a.'.repeat(126)}com`,
      '',
      42,
      null,
    ];
    const r = validateHosts(bad, OPTS);
    expect(r.hosts).toEqual([]);
    expect(r.dropped.length).toBe(bad.length);
    expect(r.dropped.find((d) => d.host === 'app.localhost')?.reason).toBe('denied');
    expect(r.dropped.find((d) => d.host === '42')?.reason).toBe('invalid');
  });

  test('drops the store domain, names under it and denied platform hosts', () => {
    const r = validateHosts(
      [
        'vendua.com.br',
        'loja.vendua.com.br',
        'a.b.vendua.com.br',
        'painel.example.com',
        'site.example.com',
        'notvendua.com.br',
        'loja.com.br',
      ],
      OPTS,
    );
    expect(r.hosts).toEqual(['loja.com.br', 'notvendua.com.br']);
    expect(r.dropped).toEqual([
      { host: 'vendua.com.br', reason: 'store-domain' },
      { host: 'loja.vendua.com.br', reason: 'store-domain' },
      { host: 'a.b.vendua.com.br', reason: 'store-domain' },
      { host: 'painel.example.com', reason: 'denied' },
      { host: 'site.example.com', reason: 'denied' },
    ]);
  });

  test('caps the list, dropping the tail of the sorted hosts', () => {
    const r = validateHosts(['d.com', 'c.com', 'b.com', 'a.com'], { ...OPTS, maxHosts: 2 });
    expect(r.hosts).toEqual(['a.com', 'b.com']);
    expect(r.dropped).toEqual([
      { host: 'c.com', reason: 'over-cap' },
      { host: 'd.com', reason: 'over-cap' },
    ]);
  });

  test('isDnsName bounds', () => {
    expect(isDnsName(`${'a'.repeat(63)}.com`)).toBe(true);
    const long = `${'abcdefghi.'.repeat(24)}abcdefghij.com`; // 254 chars
    expect(long.length).toBe(254);
    expect(isDnsName(long)).toBe(false);
    expect(isDnsName(long.slice(1))).toBe(true);
  });
});
