// The admin's screens and how-tos as Duá reads them (load_context "painel"). Its source of truth is
// the admin's Ajuda (apps/admin/src/features/help/topics.tsx): when a screen gains or loses a
// feature, both change in the same commit, and copilot-context.test.ts fails on a topic missing
// here. Numbers are spelled out: a digit with "h" or "min" reads as a typed time to `grounded`.

export const GUIDE: Record<string, string> = {
  inicio: `Início (/): o resumo do dia e "Precisa de você" (pedido sem aceite, produto acabando, cada linha com o botão para resolver). Pausar: tocar no status lá em cima e em "pausar agora", escolher por quanto tempo e, se quiser, deixar um recado. Mudar só o horário de hoje: tocar no status e em "Mudar o horário de hoje". Aviso de cada pedido no celular: Meu perfil › Avisos no celular › testar aviso.`,
  pedidos: `Pedidos (/pedidos): aceitar escolhendo o tempo de preparo no cartão (no celular, arrastar para a direita); o botão grande do cartão leva o pedido adiante (em preparo, pronto ou saiu para entrega, entregue). Cancelar: abrir o pedido (ou arrastar para a esquerda) › cancelar pedido, escolher o motivo e segurar o botão; pago pelo Mercado Pago, o dinheiro volta sozinho. No pedido: WhatsApp para mandar mensagem pronta ao cliente, imprimir comanda. Encomendas (calendário) e Histórico ficam no topo; "Tela ligada" impede o celular de apagar.`,
  cardapio: `Cardápio (/cardapio): novo produto, ou "colar lista" (cada linha com nome e preço, como "Pudim - 12", vira um produto), ou importar de outro sistema (/cardapio/importar). Esgotado hoje: no modo lista, tocar em disponível ou arrastar para a esquerda; volta sozinho à meia-noite. Dentro do produto: Dias e horários (só em alguns dias), Opções (sabor, tamanho), Estoque (ou todos em /cardapio/estoque), Encomenda (pedir com antecedência) e Kit (o cliente monta). Ordem: na grade, segurar a foto e arrastar. Vários de uma vez: "selecionar" muda disponibilidade, categoria ou preço em porcentagem.`,
  loja: `Loja (/loja): Horários (tocar no dia; feriados em "Feriados e dias especiais", sem mexer na semana). Fora do horário o cliente monta a sacola mas só finaliza quando abrir, exceto encomendas com "Encomendas com a loja fechada" ligado. Entrega e retirada: áreas por bairro ou distância, cada uma com taxa e tempo; pedido mínimo da loja toda; "Cobrar pela distância" com a loja marcada no mapa (taxa de saída mais valor por km, com mínima e distância máxima; as áreas ficam de reserva). Retirada: "Onde retirar" e "Como retirar". Mensagens: recado de pausa e de fechada; "Muitos pedidos agora" avisa que o preparo demora mais. "Falta pagar o plano": a loja abre quando o primeiro pagamento do plano é confirmado, em Conta e plano.`,
  pagamentos: `Pagamentos (/pagamentos, só o dono muda): ligar ou desligar cada forma em Formas de pagamento. Com o Mercado Pago conectado o Pix se confirma sozinho e o cartão pelo site funciona (o Mercado Pago desconta a taxa dele); sem ele, o cliente paga na chave Pix e a loja confere no app do banco antes de marcar como pago, em "Pix para conferir" ou dentro do pedido.`,
  whatsapp: `WhatsApp (/whatsapp): conectar digitando o número da loja e gerando o código; no celular da loja, WhatsApp › Aparelhos conectados › Conectar aparelho › Conectar com número de telefone, e digitar o código. A Venduá entra como aparelho conectado, o celular continua normal. Avisos aos clientes: os que estão ligados; o cliente para com SAIR e volta com VOLTAR. Desconecta quando removem a Venduá dos aparelhos ou o celular fica muitos dias sem abrir o WhatsApp: conectar de novo com um código novo.`,
  impressoras: `Impressoras (/impressoras): instalar o app Venduá Impressora no Windows ou num tablet Android ligado à impressora, abrir, e em "conectar aparelho" digitar o código que o app mostra. Serve impressora térmica de cinquenta e oito ou oitenta milímetros (Epson, Elgin, Bematech, Daruma e genéricas) por USB, rede ou Bluetooth; no Windows, instalada como impressora do Windows. Com "imprimir pedidos sozinha", sai ao aceitar ou ao chegar, como escolhido em Quando imprimir. Aparelho desligado: imprime o atrasado quando liga, até duas horas depois. Acento errado: trocar Acentos e imprimir teste.`,
  clientes: `Clientes (/clientes): todos que já pediram, pelo telefone, com pedidos, o que mais pede, último endereço e cartão fidelidade; ordenar por recentes, quem mais gastou ou mais pedidos. LGPD: abrir o cliente › "Dados pessoais (LGPD)" para exportar ou apagar.`,
  marketing: `Marketing (/marketing): Compartilhar a loja (link, WhatsApp, QR code para imprimir); Cupons (porcentagem, valor fixo ou entrega grátis); Cartão fidelidade (cada pedido entregue vale um selo, os selos viram prêmio); Lista de espera (quem quer saber quando um esgotado voltar); "Aviso na loja" (faixa no topo: promoção, novidade, recado).`,
  aparencia: `Aparência (/aparencia): tocar na parte da página para editar (no celular o nome aparece embaixo); a prévia muda na hora e os clientes só veem depois de "publicar". Versões: voltar a uma anterior (publica de novo). "Cores e cantos" no alto da lista, com aviso se ficar difícil de ler. Subir, descer, esconder ou adicionar partes; topo e rodapé valem para todas as páginas. Desfazer, ou "descartar" para voltar ao que está no ar.`,
  relatorios: `Relatórios (/relatorios): números do período escolhido comparados com o período anterior do mesmo tamanho (tocar no número explica); entrega por área; onde pediram e a loja não entrega (pode valer uma área nova em Loja › Entrega e retirada); "baixar planilha" com os pedidos do período.`,
  equipe: `Equipe (/equipe, só o dono convida): "adicionar pessoa" com nome, celular e papel; o convite vai pelo WhatsApp (e e-mail, se informado); "reenviar convite" se não chegou. Atendente cuida dos pedidos e pausa a loja; gerente também cardápio, loja, clientes, marketing e relatórios; dono pode tudo, inclusive pagamentos, equipe e plano. Tirar acesso: tocar na pessoa e segurar "tirar o acesso".`,
  conta: `Conta e plano (/conta, só o dono): plano, faturas e endereço da loja. Pagar pelo cartão (renova sozinho todo mês pelo Mercado Pago) ou por Pix (uma fatura por mês com código para copiar). Domínio próprio no plano Venduá PRO+: o painel mostra o que configurar e confere.`,
  perfil: `Meu perfil (/perfil): avisos no celular (testar aviso, lista de aparelhos), som do pedido novo (tocar uma vez no painel e "testar som", celular fora do silencioso), Duá pelo WhatsApp para donos e gerentes. Se o aviso não chegar e o WhatsApp de reserva estiver ligado, donos e gerentes recebem mensagem quando um pedido espera sem aceite.`,
  vendedor: `Duá vendedor (/vendedor): o Duá que vende no WhatsApp da loja. Assumir uma conversa: "assumir" (ou responder pelo WhatsApp da loja, que pausa ele naquela conversa); "devolver" para ele voltar. Ele chama a loja quando o cliente pede uma pessoa e nos casos escolhidos em Configurar (reclamação, alergia...). Resumo do pedido, entrega e Pix vêm calculados pela loja. Ensaio: ele escreve o que responderia sem mandar. Ensinar (/vendedor/ensinar): responder o que ele não soube ou escrever uma regra. Ele nunca diz que é pessoa; o nome é sempre Duá, o jeito de falar se escolhe em Configurar.`,
  copiloto: `Copiloto (/copiloto): você, o Duá no painel. Donos e gerentes, cada um com a sua conversa. Nada muda sem o toque em confirmar no cartão ("agora não" descarta). "Nova conversa" começa do zero; o que foi confirmado continua valendo.`,
  pdv: `PDV (/pdv): Vender no balcão (tocar nos produtos, "para levar" ou "comer aqui", cobrar; dividir em formas e troco no dinheiro). Mesas (/pdv/mesas): mesa livre abre comanda, cada adição manda uma rodada para a cozinha, receber em partes até fechar. Caixa (/pdv/caixa): abrir com o troco, sangria (sai) e suprimento (entra), fechar contando cada forma. Pedido pelo QR da mesa: chega em Pedidos e vai para a cozinha quando alguém aceita; imprimir os QR em Mesas › editar mesas › imprimir todos. Só gerentes: desconto, estorno, cancelar comanda, mesas, taxa de serviço e QR.`,
};

export function guideText(): string {
  return Object.values(GUIDE).join('\n');
}
