import { createHash } from 'node:crypto';

export const MAX_HOSTS = 5_000;

export interface RenderOptions {
  /** `VENDUA_STORE_DOMAIN`: the wildcard router already serves it and every name under it */
  storeDomain: string;
  /** platform hosts (admin, CRM, site) a custom-domain router must never claim */
  deny: readonly string[];
  /** Traefik service the routers point at (file provider: name the docker provider's) */
  service: string;
  /** middleware the `web` router uses to redirect to HTTPS */
  middleware: string;
  /** ACME resolver for the `websecure` router */
  resolver: string;
  maxHosts?: number;
}

export interface Dropped {
  host: string;
  reason: 'invalid' | 'store-domain' | 'denied' | 'over-cap';
}

const LABEL_RE = /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$/;
const TLD_RE = /^([a-z]{2,63}|xn--[a-z0-9-]{1,59})$/;

export function isDnsName(host: string): boolean {
  if (host.length > 253) return false;
  const labels = host.split('.');
  if (labels.length < 2) return false;
  if (!labels.every((l) => LABEL_RE.test(l))) return false;
  return TLD_RE.test(labels[labels.length - 1]!);
}

/** The hosts that may get a router, sorted and unique, plus what was dropped and why. Runs
 *  whatever Core sent through the same rules, so a bad row can't route a platform host. */
export function validateHosts(
  input: readonly unknown[],
  o: Pick<RenderOptions, 'storeDomain' | 'deny' | 'maxHosts'>,
): { hosts: string[]; dropped: Dropped[] } {
  const store = o.storeDomain.trim().toLowerCase();
  const deny = new Set(o.deny.map((h) => h.trim().toLowerCase()).filter(Boolean));
  const ok = new Set<string>();
  const dropped: Dropped[] = [];
  for (const raw of input) {
    const host = typeof raw === 'string' ? raw : String(raw);
    if (typeof raw !== 'string' || !isDnsName(host)) dropped.push({ host, reason: 'invalid' });
    else if (host === 'localhost' || host.endsWith('.localhost'))
      dropped.push({ host, reason: 'denied' });
    else if (store && (host === store || host.endsWith(`.${store}`)))
      dropped.push({ host, reason: 'store-domain' });
    else if (deny.has(host)) dropped.push({ host, reason: 'denied' });
    else ok.add(host);
  }
  const hosts = [...ok].sort();
  const cap = o.maxHosts ?? MAX_HOSTS;
  for (const host of hosts.splice(cap)) dropped.push({ host, reason: 'over-cap' });
  return { hosts, dropped };
}

/** `vendua-cd-<host, dots → dashes>-<8 hex of sha256(host)>`: readable, and the hash keeps
 *  `a-b.com` and `a.b.com` apart. */
export function routerName(host: string): string {
  const hash = createHash('sha256').update(host).digest('hex').slice(0, 8);
  return `vendua-cd-${host.replaceAll('.', '-')}-${hash}`;
}

// JSON strings are valid YAML double-quoted scalars; hosts are validated ASCII anyway.
const q = (s: string) => JSON.stringify(s);

const HEADER = [
  '# Generated by domains-sync (packages/domains-sync) from Core GET /sync/v1/custom-hosts.',
  '# Do not edit: it is rewritten whenever the list of custom domains changes (ADR 0038).',
];

/** Traefik dynamic configuration for already-validated `hosts`: per host a `websecure` router
 *  with an ACME certificate and a `web` router redirecting to HTTPS, both to the edge. Same
 *  input, same bytes. */
export function renderConfig(hosts: readonly string[], o: RenderOptions): string {
  // Traefik rejects an empty `routers: {}` ("cannot be a standalone element"), and one bad file
  // drops the whole file provider (Dokploy's redirect-to-https@file with it): no hosts, no keys.
  if (hosts.length === 0) return `${[...HEADER, '# No custom domains yet.'].join('\n')}\n`;
  const lines = [...HEADER, 'http:', '  routers:'];
  for (const host of [...hosts].sort()) {
    const name = routerName(host);
    const rule = q(`Host(\`${host}\`)`);
    lines.push(
      `    ${q(name)}:`,
      `      rule: ${rule}`,
      `      entryPoints: [${q('websecure')}]`,
      `      service: ${q(o.service)}`,
      `      priority: 2`,
      `      tls:`,
      `        certResolver: ${q(o.resolver)}`,
      `    ${q(`${name}-web`)}:`,
      `      rule: ${rule}`,
      `      entryPoints: [${q('web')}]`,
      `      service: ${q(o.service)}`,
      `      middlewares: [${q(o.middleware)}]`,
      `      priority: 2`,
    );
  }
  return `${lines.join('\n')}\n`;
}
